### ISSUE TITLE
Task edit does not work sometimes 

### ISSUE THREAD

**Issue by mberezuns** [knoxy5467/a-better-notion#100]
Trying to edit a task right after creating it does not do anything and client has to be restarted to be able to edit and see changes.

**Comment by vishweshRox** [comment]
NEWLY CREATED TASKS UNEDITABLE

Issue Type: Software Bug
Description: Extension to Issue 93, newly created tasks cannot be edited. Same workaround of restarting the client (as in the case of Issue 93). Delete functionality, however, works without any problems.
