### ISSUE TITLE
Dates and Chronological Ordering

### ISSUE THREAD

**Issue by vishweshRox** [knoxy5467/a-better-notion#106]
Issue Type: Feature Request
Description: It would be useful to allow the re-ordering of tasks, as well as the functionality to create tasks in specified parts of the list (i.e. an insert functionality).  It would also be useful to automatically log the date/time of creation for each task, automatically display it on the right side of the window, and enable a sorting functionality that will sort re-ordered tasks in chronological order.

**Comment by knoxy5467** [comment]
This is a planned feature for the 1.0 release. this issue is being rolled into #91
