### ISSUE TITLE
Send requests to /task and /filterid to get middleware init data for alpha release.

### ISSUE THREAD

**Issue by jacobe90** [knoxy5467/a-better-notion#31]
Middleware needs to call the function to get tasks with the server API, and add those tasks to state in init.
Relevant Code: [https://github.com/knoxy5467/a-better-notion/blob/main/server/src/api.rs#L32](https://github.com/knoxy5467/a-better-notion/blob/main/server/src/api.rs#L32
)

Priority: High
Timeline: 1 day

**Comment by knoxy5467** [comment]
alpha release was forever ago
