### ISSUE TITLE
Revise SDS and SRS for submission; resubmit before beta is due

### ISSUE THREAD

**Issue by jxsminengo** [knoxy5467/a-better-notion#65]
- review graded comments
- An updated system requirements specification (SRS) and system design specification and plan (SDS)
documents, with change tracking on. Focus on the content changes, not the polish. If you have changed
your feature list delivery schedule, add a note discussing the tradeoffs involved in making this decision. --> resubmit these once reviewed before beta is due

**Comment by knoxy5467** [comment]
Was reveiwed and submitted with beta
